---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: splunk-connector-logging
  namespace: flux-system
spec:
  chart:
    spec:
      chart: splunk-connect-for-kubernetes
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: splunk-connector
  interval: 1m0s
  values:
    global:
      logLevel: info