---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: splunk-connector-logging
  namespace: flux-system
spec:
  chart:
    spec:
      chart: splunk-connect-for-kubernetes
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: splunk-connector
  interval: 1m0s
  values:
    global:
      splunk:
        hec:
          host: prd-p-mssza.splunkcloud.com
          indexName: main
          port: 443
      logLevel: info
    splunk-kubernetes-logging:
      enabled: true
      containers:
        logFormatType: cri
    splunk-kubernetes-objects:
      enabled: false
    splunk-kubernetes-metrics:
      enabled: false
  valuesFrom:
    - kind: Secret
      name: splunk-token
      valuesKey: token
      targetPath: global.splunk.hec.token
      optional: false